
mru_transform/sensors:
 - name: posmv
   topics: { position: 'sensors/posmv/position', orientation: 'sensors/posmv/orientation', velocity: 'sensors/posmv/velocity'}
 - name: gps
   topics: { position: 'sensors/oem/sync/position', orientation: 'sensors/oem/sync/orientation', velocity: 'sensors/oem/sync/velocity'}
      
helm_manager/output_type: 'dual'
helm_manager/max_yaw_speed: 0.5
helm_manager/max_speed: 2.75

asv_helm/pid/Kp: 0.36
asv_helm/pid/Ki: 1.0
asv_helm/pid/Kd: 0.01
asv_helm/pid/upper_limit: 1.0
asv_helm/pid/lower_limit: -1.0
asv_helm/pid/windup_limit: 1.0
asv_helm/pid/max_dt: 1.0

udp_bridge/remotes:
    operator:
        topics:
          asv_helm_pid: {source: asv_helm/pid/debug}
          autonomous_cmd_vel: {source: project11/piloting_mode/autonomous/cmd_vel}
          control_cmd_vel: {source: project11/control/cmd_vel}
          odom: {source: project11/odom}
          sensors_cameras_pano_1_yolo4_detections: {source: sensors/cameras/pano_1/yolo4/detections}
          sensors_cameras_pano_2_yolo4_detections: {source: sensors/cameras/pano_2/yolo4/detections}
          sensors_cameras_pano_3_yolo4_detections: {source: sensors/cameras/pano_3/yolo4/detections}
          sensors_cameras_pano_4_yolo4_detections: {source: sensors/cameras/pano_4/yolo4/detections}
          sensors_cameras_pano_5_yolo4_detections: {source: sensors/cameras/pano_5/yolo4/detections}
          sensors_cameras_pano_6_yolo4_detections: {source: sensors/cameras/pano_6/yolo4/detections}
          sensors_cameras_pano_1_camera_info: {source: sensors/cameras/pano_1/camera_info}
          sensors_cameras_pano_2_camera_info: {source: sensors/cameras/pano_2/camera_info}
          sensors_cameras_pano_3_camera_info: {source: sensors/cameras/pano_3/camera_info}
          sensors_cameras_pano_4_camera_info: {source: sensors/cameras/pano_4/camera_info}
          sensors_cameras_pano_5_camera_info: {source: sensors/cameras/pano_5/camera_info}
          sensors_cameras_pano_6_camera_info: {source: sensors/cameras/pano_6/camera_info}
          navigator_costmap: {source: navigator/costmap/costmap}
          navigator_costmap_updates: {source: navigator/costmap/costmap_updates}
          sensors_lidar_costmap: {source: sensors/lidar/projected_map}
          sensors_radar_haloa_costmap: {source: sensors/radar/HaloA/costmap/costmap/costmap}
          sensors_radar_haloa_costmap_updates: {source: sensors/radar/HaloA/costmap/costmap/costmap_updates}
          sensors_radar_halob_costmap: {source: sensors/radar/HaloB/costmap/costmap/costmap}
          sensors_radar_halob_costmap_updates: {source: sensors/radar/HaloB/costmap/costmap/costmap_updates}
