
mru_transform/sensors:
 - name: posmv
   topics: { position: 'sensors/posmv/position', orientation: 'sensors/posmv/orientation', velocity: 'sensors/posmv/velocity'}
 - name: gps
   topics: { position: 'sensors/oem/position', orientation: 'sensors/oem/orientation', velocity: 'sensors/oem/velocity'}
      
helm_manager/output_type: 'helm'
helm_manager/max_yaw_speed: 0.5
helm_manager/max_speed: 2.75

asv_helm/pid/Kp: 0.36
asv_helm/pid/Ki: 1.0
asv_helm/pid/Kd: 0.01
asv_helm/pid/upper_limit: 1.0
asv_helm/pid/lower_limit: -1.0
asv_helm/pid/windup_limit: 1.0
asv_helm/pid/max_dt: 1.0

project11/platforms/ben:
  robot_description: ben/robot_description
  width: 1.7
  length: 4.25
  reference_x: 0.525
  nav_sources:
    posmv:
      position_topic: /ben/sensors/posmv/position
      orientation_topic: /ben/sensors/posmv/orientation
      velocity_topic: /ben/sensors/posmv/velocity
    nav:
      position_topic: /ben/sensors/nav/position
      orientation_topic: /ben/sensors/nav/orientation
      velocity_topic: /ben/sensors/nav/velocity
    oem:
      position_topic: /ben/sensors/oem/position
      orientation_topic: /ben/sensors/oem/orientation
      velocity_topic: /ben/sensors/oem/velocity
  color:
    red: 1.0
    green: 0.8
    blue: 0.1


s57_grids:
  map_frame: ben/map

  robot:
    frame_id: ben/base_link
    minimum_depth: 0.0
    maximum_caution_depth: 3.0
    overhead_clearance: 4.0
    minimum_speed: 0.01
    maximum_speed: 2.75

  grids:
    - name: global
      resolution: 6.0
      length: 15000.0
      period: 30.0
    - name: local
      resolution: 2.0
      length: 5000.0
      period: 1.0


udp_bridge/remotes:
    operator:
        topics:
          asv_helm_pid: {source: asv_helm/pid/debug}
          autonomous_cmd_vel: {source: project11/piloting_mode/autonomous/cmd_vel}
          control_cmd_vel: {source: project11/control/cmd_vel}
          halo_a_grid: {source: sensors/radar/HaloA/grid_map}
          nav_visualization_markers: {source: navigator/visualization_markers}
          odom: {source: project11/odom}
          sensors_cameras_pano_1_yolo4_detections: {source: sensors/cameras/pano_1/yolo4/detections}
          sensors_cameras_pano_2_yolo4_detections: {source: sensors/cameras/pano_2/yolo4/detections}
          sensors_cameras_pano_3_yolo4_detections: {source: sensors/cameras/pano_3/yolo4/detections}
          sensors_cameras_pano_4_yolo4_detections: {source: sensors/cameras/pano_4/yolo4/detections}
          sensors_cameras_pano_5_yolo4_detections: {source: sensors/cameras/pano_5/yolo4/detections}
          sensors_cameras_pano_6_yolo4_detections: {source: sensors/cameras/pano_6/yolo4/detections}
          sensors_cameras_pano_1_camera_info: {source: sensors/cameras/pano_1/camera_info}
          sensors_cameras_pano_2_camera_info: {source: sensors/cameras/pano_2/camera_info}
          sensors_cameras_pano_3_camera_info: {source: sensors/cameras/pano_3/camera_info}
          sensors_cameras_pano_4_camera_info: {source: sensors/cameras/pano_4/camera_info}
          sensors_cameras_pano_5_camera_info: {source: sensors/cameras/pano_5/camera_info}
          sensors_cameras_pano_6_camera_info: {source: sensors/cameras/pano_6/camera_info}
          sensors_lidar_costmap: {source: sensors/lidar/projected_map}
          s57_local_grid: {source: s57_grids/grids/local}
          
