
mru_transform/sensors:
 - name: posmv
   topics: { position: 'sensors/posmv/position', orientation: 'sensors/posmv/orientation', velocity: 'sensors/posmv/velocity'}
 - name: gps
   topics: { position: 'sensors/oem/position', orientation: 'sensors/oem/orientation', velocity: 'sensors/oem/velocity'}
      
helm_manager/output_type: 'helm'
helm_manager/max_yaw_speed: 0.5
helm_manager/max_speed: 2.75

asv_helm/pid/Kp: 0.36
asv_helm/pid/Ki: 1.0
asv_helm/pid/Kd: 0.01
asv_helm/pid/upper_limit: 1.0
asv_helm/pid/lower_limit: -1.0
asv_helm/pid/windup_limit: 1.0
asv_helm/pid/max_dt: 1.0

s57_grids:
  map_frame: ben/map

  robot:
    frame_id: ben/base_link
    minimum_depth: 0.0
    maximum_caution_depth: 3.0
    overhead_clearance: 4.0
    minimum_speed: 0.01
    maximum_speed: 2.75

  grids:
    - name: global
      resolution: 25.0
      length: 175000.0
      period: 30.0
    - name: area
      resolution: 6.0
      length: 15000.0
      period: 30.0
    - name: local
      resolution: 3.0
      length: 5000.0
      period: 1.0


udp_bridge:
  name: ben
  remotes:
    operator:
      connections:
        default:
          topics:
            asv_helm_pid: {source: asv_helm/pid/debug}
            autonomous_cmd_vel: {source: project11/piloting_mode/autonomous/cmd_vel}
            control_cmd_vel: {source: project11/control/cmd_vel}
            nav_visualization_markers: {source: navigator/visualization_markers}
            odom: {source: odom}
            s57_local_grid: {source: s57_grids/grids/local}

   
