udp_bridge/remotes:
    robot_vpn:
        name: ben_vpn
        host: mystiquev
        port: 4200
        returnHost: salmon
        returnPort: 4200
        maxPacketSize: 1200
        topics:
          project11_command: {source: project11/command}
          piloting_mode_manual_helm: {source: project11/piloting_mode/manual/helm}
