plugins: 
- {name: chart,            type: "s57_layer::S57Layer"}
- {name: inflation,        type: "costmap_2d::InflationLayer"}
publish_frequency: 1.0
update_frequency: 1.0
rolling_window: true
width: 20000
height: 20000
resolution: 3

chart:
    foo: bar

inflation:
    inflation_radius: 100
    cost_scaling_factor: 0.05
