robot:
  turn_radius:
  - velocity: 0.5
    radius: 2.0
  - velocity: 2.75
    radius: 10.0
  
  max_velocity:
    linear/x: 2.75

  default_velocity:
    linear/x: 2.5

  min_velocity:
    linear/x: 0.5

  footprint: [[2.65, 0], [2.6, 0.1], [2.4, 0.4], [1.9, 0.6], [1.0, 0.85], [-1.3, 0.85], [-1.35, 0.4], [-1.6, 0.35], [-1.6, -0.35], [-1.35, -0.4], [-1.3, -0.85], [1.0, -0.85], [1.9, -0.6], [2.4, -0.4], [2.6, -0.1], [2.65, 0]]

plugins:
  TaskToTaskWorkflow:
    ccom_planner: ccom_planner/Planner

TaskToTwistWorkflow/transit:
  steps:
    - ccom_planner
  last_step: path_follower

TaskToTwistWorkflow/path_follower:
  pid:
    Kp: 6.0
    Ki: 0.5
    Kd: 0.6

grids:
  static:
    chart_global: s57_grids/grids/global
    chart_area: s57_grids/grids/area
    chart_local: s57_grids/grids/local
  dynamic:
    halo_a: sensors/radar/HaloA/grid_map

costmap:
    plugins: 
    - {name: chart,            type: "s57_layer::S57Layer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    publish_frequency: 0.5
    update_frequency: 0.5
    rolling_window: true
    width: 3000
    height: 3000
    resolution: 1.5
    always_send_full_costmap: true

    inflation:
      inflation_radius: 150
      cost_scaling_factor: 0.006

    chart:
      update_timeout: 1.0
      minimum_depth: 0.5
      maximum_caution_depth: 10.0

    global_frame: ben/map
    robot_base_frame: ben/base_link
    max_obstacle_height: 5
    footprint: [[2.65, 0], [2.6, 0.1], [2.4, 0.4], [1.9, 0.6], [1.0, 0.85], [-1.3, 0.85], [-1.35, 0.4], [-1.6, 0.35], [-1.6, -0.35], [-1.35, -0.4], [-1.3, -0.85], [1.0, -0.85], [1.9, -0.6], [2.4, -0.4], [2.6, -0.1], [2.65, 0]]

