robot:
  turn_radius:
  - velocity: 0.5
    radius: 2.0
  - velocity: 2.75
    radius: 10.0
  
  max_velocity:
    linear/x: 2.75

  default_velocity:
    linear/x: 2.5

  min_velocity:
    linear/x: 0.5

  footprint: [[2.65, 0], [2.6, 0.1], [2.4, 0.4], [1.9, 0.6], [1.0, 0.85], [-1.3, 0.85], [-1.35, 0.4], [-1.6, 0.35], [-1.6, -0.35], [-1.35, -0.4], [-1.3, -0.85], [1.0, -0.85], [1.9, -0.6], [2.4, -0.4], [2.6, -0.1], [2.65, 0]]

waypoint_reached_distance: 5.0
survey_lead_in_distance: 3.5

plugins:
  TaskToTaskWorkflow:
    ccom_planner: ccom_planner/Planner

# following moved to navigator_ccom_planner.yaml
# TaskToTwistWorkflow/transit:
#   steps:
#     - ccom_planner
#   last_step: path_follower

TaskToTwistWorkflow/path_follower:
  pid:
    Kp: 6.0
    Ki: 0.5
    Kd: 0.6

TaskToTwistWorkflow/hover:
  maximum_distance: 5.0
  minimum_distance: 2.0
  maximum_speed: 1.5


grids:
  static:
    chart_global: s57_grids/grids/global
    chart_area: s57_grids/grids/area
    chart_local: s57_grids/grids/local
  dynamic:
    halo_a: sensors/radar/HaloA/grid_map

hover:
  maximum_distance: 5.0
  minimum_distance: 2.0
  maximum_speed: 1.5

path_follower:
  pid:
    Kp: 6.0
    Ki: 0.5
    Kd: 0.6
