map_frame: ben/map

robot:
  frame_id: ben/base_link
  minimum_depth: 0.25
  maximum_caution_depth: 3.0
  overhead_clearance: 4.0
  minimum_speed: 0.5
  maximum_speed: 2.75

grids:
  - name: global
    resolution: 6.0
    length: 15000.0
    period: 30.0
  - name: local
    resolution: 2.0
    length: 5000.0
    period: 1.0
